[theme]
base = "light"
primaryColor = "#1b5a7a"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#212529"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501