[theme]
hide_menu = true
base = "light"
primaryColor = "#264653"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#212529"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501